Update argocd.yml

diff --git a/.github/workflows/argocd.yml b/.github/workflows/argocd.yml
--- a/.github/workflows/argocd.yml
+++ b/.github/workflows/argocd.yml
@@ -21,6 +21,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Verify Dockerfile exists
+        run: |
+          if [ ! -f ./WebApplication1/Dockerfile ]; then
+            echo "Dockerfile not found!"
+            exit 1
+          fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -34,7 +41,7 @@ jobs:
 
       - name: Build Docker image
         run: |
-          docker build -t $ECR_REPOSITORY:latest .
+          docker build -t $ECR_REPOSITORY:latest -f ./WebApplication1/Dockerfile .
           docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
 
       - name: Push Docker image to Amazon ECR
@@ -55,7 +62,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: $AWS_REGION
+          aws-region: us-east-1
 
       - name: Update Helm values.yaml with new image
         run: |
@@ -70,7 +77,7 @@ jobs:
 
       - name: Log in to Argo CD
         run: |
-          argocd login $ARGOCD_SERVER --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
+          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
 
       - name: Sync Argo CD application
         run: |
